import type { OrganizationNamespace, XyteCallArgs } from '../../types/client';

export function createOrganizationNamespace(
  call: (endpointKey: string, args?: XyteCallArgs) => Promise<unknown>
): OrganizationNamespace {
  return {
    closeIncident: (args) => call('organization.incidents.closeIncident', args),
    cancelCommand: (args) => call('organization.commands.cancelCommand', args),
    getCommands: (args) => call('organization.commands.getCommands', args),
    sendCommand: (args) => call('organization.commands.sendCommand', args),
    claimDevice: (args) => call('organization.devices.claimDevice', args),
    moveDevice: (args) => call('organization.devices.moveDevice', args),
    suspendIncidents: (args) => call('organization.devices.suspendIncidents', args),
    resumeIncidents: (args) => call('organization.devices.resumeIncidents', args),
    updateDevice: (args) => call('organization.devices.updateDevice', args),
    deleteDevice: (args) => call('organization.devices.deleteDevice', args),
    getDevice: (args) => call('organization.devices.getDevice', args),
    getDevices: (args) => call('organization.devices.getDevices', args),
    getHistories: (args) => call('organization.devices.getHistories', args),
    startEdgeClaim: (args) => call('organization.edge.startClaim', args),
    getEdgeClaimStatus: (args) => call('organization.edge.getClaimStatus', args),
    startEdgePing: (args) => call('organization.edge.startPing', args),
    getEdgePingStatus: (args) => call('organization.edge.getPingStatus', args),
    listEdges: (args) => call('organization.edges.listEdges', args),
    getOrganizationInfo: (args) => call('organization.getOrganizationInfo', args),
    addExternalUserToGroup: (args) => call('organization.groups.addExternalUser', args),
    addUsersToGroup: (args) => call('organization.groups.addUsers', args),
    createGroup: (args) => call('organization.groups.createGroup', args),
    deleteGroup: (args) => call('organization.groups.deleteGroup', args),
    getGroup: (args) => call('organization.groups.getGroup', args),
    listGroups: (args) => call('organization.groups.listGroups', args),
    removeUsersFromGroup: (args) => call('organization.groups.removeUsers', args),
    updateGroup: (args) => call('organization.groups.updateGroup', args),
    getIncidents: (args) => call('organization.incidents.getIncidents', args),
    createSpace: (args) => call('organization.spaces.createSpace', args),
    deleteSpace: (args) => call('organization.spaces.deleteSpace', args),
    findOrCreateSpace: (args) => call('organization.spaces.findOrCreateSpace', args),
    getSpace: (args) => call('organization.spaces.getSpace', args),
    getSpaces: (args) => call('organization.spaces.getSpaces', args),
    updateSpace: (args) => call('organization.spaces.updateSpace', args),
    getTicket: (args) => call('organization.tickets.getTicket', args),
    getTickets: (args) => call('organization.tickets.getTickets', args),
    markResolved: (args) => call('organization.tickets.markResolved', args),
    sendMessage: (args) => call('organization.tickets.sendMessage', args),
    updateTicket: (args) => call('organization.tickets.updateTicket', args),
    createUser: (args) => call('organization.users.createUser', args),
    deactivateUser: (args) => call('organization.users.deactivateUser', args),
    getUser: (args) => call('organization.users.getUser', args),
    listUsers: (args) => call('organization.users.listUsers', args),
    resendWelcome: (args) => call('organization.users.resendWelcome', args)
  };
}
